### ISSUE TITLE
10.5 - Still require ESMP?

### ISSUE THREAD

**Issue by simongis** [Esri/network-analysis-services#12]
At 10.4.1, I understand that the Analysis services require the Street Map Premium product to be used for the analysis services.  Is this still the same at 10.5?

**Comment by deelesh** [comment]
Yes this is still the case at 10.5. However we have an action item on our list to support any network dataset (as long as it meets a minimum schema).

We are still evaluating the priority of this enhancement. So in case you have some feedback (for example, scenarios where ESMP cannot be used, or even a schema for the network dataset you wish was supported with these services) please send them to dmandloi@esri.com.

**Comment by simongis** [comment]
@deelesh - can you confirm that you can now use your own NA service.

I saw at th[e following help link:](http://enterprise.arcgis.com/en/server/latest/administer/linux/publishing-routing-services.htm)

If you are using your own network dataset, it must satisfy the following conditions:

Has at least one time-based and one distance-based cost attribute
Defines at least one travel mode
Stored in a file geodatabase
Supports directions

**Comment by deelesh** [comment]
@simongis 
Yes using your own network datasets (as long as they meet the minimum criteria) is supported with ArcGIS Enterprise 10.5 or later.
