### ISSUE TITLE
Geocoding

### ISSUE THREAD

**Issue by simongis** [Esri/network-analysis-services#2]
Not sure if this is the right place to ask, but as SMP also provides geocoding, is there a similar guide on how to set that up for geocoding?  Or for geocoding, can I use my own geocoder that is served up from ArcGIS Server?

**Comment by deelesh** [comment]
While this repo is for network-analysis services, I think I can help you if I understand in more detail on what you are trying to achieve.

Can you elaborate on how you intend to use geocoding service that is published from SMP geocoding content? Are you trying to use such a service with your on-premises portal? or you want to use it with arcgis.com portal?

**Comment by simongis** [comment]
With Portal for ArcGIS.  I understand that the SMP also enables geocoding.  From what I understand, I think that the geocoding service that you can plug into a Portal is less 'strict' than the network analysis services.  As in, it can be any geocoding service you publish to your GIS Server?  Completely understand why for the network analysis services they rely on the specific SMP data over any old routable network.  If you could perhaps just add some comments to that and then feel free to close this off, your right, does not really belong here.

**Comment by deelesh** [comment]
> From what I understand, I think that the geocoding service that you can plug into a Portal is less 'strict' than the network analysis services. As in, it can be any geocoding service you publish to your GIS Server

This is correct. You can [configure](http://server.arcgis.com/en/portal/latest/administer/windows/configure-portal-to-geocode-addresses.htm) any geocode service including the ones you can puslish using SMP data with your portal for ArcGIS. If you want to use geocode service for batch geocoding, it needs to be published on ArcGIS Server 10.1 or later.
