### ISSUE TITLE
Issue publishing to a federated hosting server

### ISSUE THREAD

**Issue by simongis** [Esri/network-analysis-services#3]
I have followed the steps in the wiki to prep the data and publish the GP service to our federated 10.4 ArcGIS Server that also includes ArcGIS Data Store.

Only have two mosaic datasets.
Believe I have followed the guide correctly and tool works fine in ArcMap.  Fails to publish to Server with the ['Consolidating the data failed'](http://resources.arcgis.com/en/help/main/10.1/index.html#//00vp0000002r001270) error. 

Any ideas how to troubleshoot this further?  Can't see anything obvious in the ArcGIS Server logs either. 

![failtopublish](https://cloud.githubusercontent.com/assets/2769383/15006988/50d8d38c-1218-11e6-8c54-25587c2fdd5d.gif)

**Comment by deelesh** [comment]
I think you have submitted the issue to the wrong repo. The correct repo to submit this issue would be https://github.com/Esri/elevation-gp-python

**Comment by simongis** [comment]
My bad! Had too many tabs open.
