### ISSUE TITLE
ESMP licensing with Analysis Services

### ISSUE THREAD

**Issue by simongis** [Esri/network-analysis-services#5]
Can someone elaborate on how the licensing/pricing works when publishing the ESMP data to analysis services?  

Is a single ESMP license applied to the ArcGIS Server machine where the service will be running, and this then allows unlimited access to the services (e.g. the analysis services, geocoding) from a portals named users without purchasing additional user licenses for ESMP? 

I also noticed when reading the [technical restrictions on using ESMP](http://server.arcgis.com/en/streetmap-premium/latest/get-started/tech-rest.htm):

> You also cannot use any ArcGIS function that will read from the Streets or Routing_Streets Shape field and output features into a feature class (for example, buffer, intersect, and so on).

The analysis services create hosted feature services from the HERE data (we are in Asia Pacific, and only have option to use HERE data for Australia) - does this not conflict with the terms of use?

**Comment by simongis** [comment]
[This link for technical restrictions](http://server.arcgis.com/en/streetmap-premium/latest/get-started/tech-rest.htm) is more fitting as from the ArcGIS for Server help.

**Comment by deelesh** [comment]
I have asked our ESMP product manager, Scott Sandusky,  to get in touch with you with regards to ESMP licensing for ArcGIS Server.

But once you have the appropriate license for ESMP on the server, you can always create and store and derivatives such as routes or service area polygons created by running network analysis services using ESMP data. 

ESMP data license (and even ArcGIS software) prevents you from exporting the raw streets features from ESMP which is what you pointed out.

**Comment by simongis** [comment]
This can be closed off.  Scott got in touch.  We need the Server license for ESMP and not a per user license.  Thanks.
